In [1]:
import numpy as np
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('gplay.csv')
df.head()

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      10841 non-null  int64
 1   App             10841 non-null  object
 2   Category        10841 non-null  object
 3   Rating          9367 non-null   float64
 4   Reviews         10841 non-null  object
 5   Size            10841 non-null  object
 6   Installs        10841 non-null  object
 7   Type            10840 non-null  object
 8   Price           10841 non-null  object
 9   Content Rating  10840 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 847.1+ KB

#### firstly we have to get rid of the unmaned columns

In [4]:
df.columns

Index(['Unnamed: 0', 'App', 'Category', 'Rating', 'Reviews', 'Size',
       'Installs', 'Type', 'Price', 'Content Rating'],
      dtype='object')

In [5]:
#copy paste the unnamed column as it is dnt write directly it will give error

df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [6]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone

#### astype function - to change the datatype

In [7]:
df.isnull().sum()   #finding missing values

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
dtype: int64

In [8]:
df.isnull().sum()/len(df)*100   #finding missing value percent wise

App                0.000000
Category           0.000000
Rating            13.596532
Reviews            0.000000
Size               0.000000
Installs           0.000000
Type               0.009224
Price              0.000000
Content Rating     0.009224
dtype: float64

In [9]:
#hence is more than 3% we need to do fillna()

rm=df['Rating'].mean()
df['Rating'].fillna(rm,inplace=True)

In [10]:
df.dropna(inplace=True)

In [11]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

In [12]:
#to drop whole dataset ka values

df['Reviews']=df['Reviews'].astype(float)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            10839 non-null  object
 5   Installs        10839 non-null  object
 6   Type            10839 non-null  object
 7   Price           10839 non-null  object
 8   Content Rating  10839 non-null  object
dtypes: float64(2), object(7)
memory usage: 846.8+ KB

In [14]:
df['Size'].value_counts()

Varies with device    1694
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
430k                     1
429k                     1
200k                     1
460k                     1
619k                     1
Name: Size, Length: 461, dtype: int64

In [19]:
def clean(x):
    if 'k' in x:
        x=x.replace('k','')
        return float(x)/1024
    elif 'M' in x:
        x=x.replace('M','')
        return float(x)
    elif 'Varies with device' in x:
        return np.nan
    else:
        return float(x)

In [20]:
df['Size']=df['Size'].map(clean)

In [21]:
df['Size'].value_counts()

11.000000    198
12.000000    196
14.000000    194
13.000000    191
15.000000    184
            ...
0.419922       1
0.418945       1
0.195312       1
0.449219       1
0.604492       1
Name: Size, Length: 459, dtype: int64

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            9145 non-null   float64
 5   Installs        10839 non-null  object
 6   Type            10839 non-null  object
 7   Price           10839 non-null  object
 8   Content Rating  10839 non-null  object
dtypes: float64(3), object(6)
memory usage: 846.8+ KB

In [23]:
df['Installs'].value_counts()

1,000,000+        1579
10,000,000+       1252
100,000+          1169
10,000+           1054
1,000+             907
5,000,000+         752
100+               719
500,000+           539
50,000+            479
5,000+             477
100,000,000+       409
10+                386
500+               330
50,000,000+        289
50+                205
5+                  82
500,000,000+        72
1+                  67
1,000,000,000+      58
0+                  14
Name: Installs, dtype: int64

In [25]:
df['Installs']=df['Installs'].str.replace('+','')
df['Installs']=df['Installs'].str.replace(',','')

In [26]:
df['Price'].value_counts()

0         10039
$0.99       148
$2.99       129
$1.99        73
$4.99        72
          ...
$19.90        1
$1.75         1
$14.00        1
$4.85         1
$1.04         1
Name: Price, Length: 92, dtype: int64

In [27]:
df['Installs']=df['Installs'].astype(float)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            9145 non-null   float64
 5   Installs        10839 non-null  float64
 6   Type            10839 non-null  object
 7   Price           10839 non-null  object
 8   Content Rating  10839 non-null  object
dtypes: float64(4), object(5)
memory usage: 846.8+ KB

In [30]:
df['Price']=df['Price'].str.replace('$','')
df['Price']=df['Price'].astype(float)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            9145 non-null   float64
 5   Installs        10839 non-null  float64
 6   Type            10839 non-null  object
 7   Price           10839 non-null  float64
 8   Content Rating  10839 non-null  object
dtypes: float64(5), object(4)
memory usage: 846.8+ KB

In [32]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19.0,10000.0,Free,0.0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14.0,500000.0,Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7,5000000.0,Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25.0,50000000.0,Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8,100000.0,Free,0.0,Everyone

In [33]:
df['Installs'].value_counts()

1.000000e+06    1579
1.000000e+07    1252
1.000000e+05    1169
1.000000e+04    1054
1.000000e+03     907
5.000000e+06     752
1.000000e+02     719
5.000000e+05     539
5.000000e+04     479
5.000000e+03     477
1.000000e+08     409
1.000000e+01     386
5.000000e+02     330
5.000000e+07     289
5.000000e+01     205
5.000000e+00      82
5.000000e+08      72
1.000000e+00      67
1.000000e+09      58
0.000000e+00      14
Name: Installs, dtype: int64

In [29]:
#now my cleaning is done my file is ready to analysis

## analysis

In [34]:
#display all the records having rating-4
df.loc[df['Rating']==4.0]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
20,Logo Maker - Small Business,ART_AND_DESIGN,4.0,450.0,14.000000,100000.0,Free,0.0,Everyone
39,How To Color Disney Princess - Coloring Pages,ART_AND_DESIGN,4.0,591.0,9.400000,500000.0,Free,0.0,Everyone
50,Real Tractor Farming,AUTO_AND_VEHICLES,4.0,1598.0,56.000000,1000000.0,Free,0.0,Everyone
58,Restart Navigator,AUTO_AND_VEHICLES,4.0,1403.0,0.196289,100000.0,Free,0.0,Everyone
66,Used Cars Mexico,AUTO_AND_VEHICLES,4.0,190.0,2.500000,50000.0,Free,0.0,Everyone
...,...,...,...,...,...,...,...,...,...
10802,FR: My Famous Lover,FAMILY,4.0,185.0,28.000000,10000.0,Free,0.0,Teen
10814,FR: My Secret Pets!,FAMILY,4.0,785.0,31.000000,50000.0,Free,0.0,Teen
10817,HTC Sense Input - FR,TOOLS,4.0,885.0,8.000000,100000.0,Free,0.0,Everyone
10826,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486.0,NaN,5000000.0,Free,0.0,Mature 17+
10834,FR Calculator,FAMILY,4.0,7.0,2.600000,500.0,Free,0.0,Everyone

In [35]:
#display all the records of the app with max. rating

df['Rating'].max()
df.loc[df['Rating']==5.0]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
329,Hojiboy Tojiboyev Life Hacks,COMICS,5.0,15.0,37.0,1000.0,Free,0.0,Everyone
612,American Girls Mobile Numbers,DATING,5.0,5.0,4.4,1000.0,Free,0.0,Mature 17+
615,Awake Dating,DATING,5.0,2.0,70.0,100.0,Free,0.0,Mature 17+
633,Spine- The dating app,DATING,5.0,5.0,9.3,500.0,Free,0.0,Teen
636,Girls Live Talk - Free Text and Video Chat,DATING,5.0,6.0,5.0,100.0,Free,0.0,Mature 17+
...,...,...,...,...,...,...,...,...,...
10721,Mad Dash Fo' Cash,GAME,5.0,14.0,16.0,100.0,Free,0.0,Everyone
10742,GKPB FP Online Church,LIFESTYLE,5.0,32.0,7.9,1000.0,Free,0.0,Everyone
10776,Monster Ride Pro,GAME,5.0,1.0,24.0,10.0,Free,0.0,Everyone
10820,Fr. Daoud Lamei,FAMILY,5.0,22.0,8.6,1000.0,Free,0.0,Teen
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4.0,3.6,100.0,Free,0.0,Everyone

In [37]:
#display only the app category and rating of app whose rating = 5.0

df[['App','Category','Rating']].loc[df['Rating']==5.0]

                                              App   Category  Rating
329                  Hojiboy Tojiboyev Life Hacks     COMICS     5.0
612                 American Girls Mobile Numbers     DATING     5.0
615                                  Awake Dating     DATING     5.0
633                         Spine- The dating app     DATING     5.0
636    Girls Live Talk - Free Text and Video Chat     DATING     5.0
...                                           ...        ...     ...
10721                           Mad Dash Fo' Cash       GAME     5.0
10742                       GKPB FP Online Church  LIFESTYLE     5.0
10776                            Monster Ride Pro       GAME     5.0
10820                             Fr. Daoud Lamei     FAMILY     5.0
10837            Fr. Mike Schmitz Audio Teachings     FAMILY     5.0

[274 rows x 3 columns]

In [38]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19.0,10000.0,Free,0.0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14.0,500000.0,Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7,5000000.0,Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25.0,50000000.0,Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8,100000.0,Free,0.0,Everyone

In [40]:
#display record of all free apps

df.loc[df['Type']=='Free']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159.0,19.0,10000.0,Free,0.0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.900000,967.0,14.0,500000.0,Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510.0,8.7,5000000.0,Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644.0,25.0,50000000.0,Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967.0,2.8,100000.0,Free,0.0,Everyone
...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38.0,53.0,5000.0,Free,0.0,Everyone
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4.0,3.6,100.0,Free,0.0,Everyone
10838,Parkinson Exercices FR,MEDICAL,4.193338,3.0,9.5,1000.0,Free,0.0,Everyone
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114.0,NaN,1000.0,Free,0.0,Mature 17+
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307.0,19.0,10000000.0,Free,0.0,Everyone

In [42]:
#display the record of most expensive app

df['App'].max()

'🔥 Football Wallpapers 4K | Full HD Backgrounds 😍'

In [41]:
#display all records of apps whose rating is between 4 and 5

df.loc[(df['Rating']>=4.0) & (df['Rating']<=5.0)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159.0,19.0,10000.0,Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510.0,8.7,5000000.0,Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644.0,25.0,50000000.0,Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967.0,2.8,100000.0,Free,0.0,Everyone
5,Paper flowers instructions,ART_AND_DESIGN,4.400000,167.0,5.6,50000.0,Free,0.0,Everyone
...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38.0,53.0,5000.0,Free,0.0,Everyone
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4.0,3.6,100.0,Free,0.0,Everyone
10838,Parkinson Exercices FR,MEDICAL,4.193338,3.0,9.5,1000.0,Free,0.0,Everyone
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114.0,NaN,1000.0,Free,0.0,Mature 17+
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307.0,19.0,10000000.0,Free,0.0,Everyone

In [43]:
#display the free app with rating = 5

df.loc[(df['Type']=='Free') & (df['Rating']==5.0)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
329,Hojiboy Tojiboyev Life Hacks,COMICS,5.0,15.0,37.0,1000.0,Free,0.0,Everyone
612,American Girls Mobile Numbers,DATING,5.0,5.0,4.4,1000.0,Free,0.0,Mature 17+
615,Awake Dating,DATING,5.0,2.0,70.0,100.0,Free,0.0,Mature 17+
633,Spine- The dating app,DATING,5.0,5.0,9.3,500.0,Free,0.0,Teen
636,Girls Live Talk - Free Text and Video Chat,DATING,5.0,6.0,5.0,100.0,Free,0.0,Mature 17+
...,...,...,...,...,...,...,...,...,...
10721,Mad Dash Fo' Cash,GAME,5.0,14.0,16.0,100.0,Free,0.0,Everyone
10742,GKPB FP Online Church,LIFESTYLE,5.0,32.0,7.9,1000.0,Free,0.0,Everyone
10776,Monster Ride Pro,GAME,5.0,1.0,24.0,10.0,Free,0.0,Everyone
10820,Fr. Daoud Lamei,FAMILY,5.0,22.0,8.6,1000.0,Free,0.0,Teen
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4.0,3.6,100.0,Free,0.0,Everyone

In [ ]:
#display all the low rated app wich belong to paid category

In [44]:
#find more 4 questions homework